# Project Information
site_name: WNotes
site_description: 个人笔记，博客
site_author: wang
site_url: https://lbwanga.github.io/
strict: false
use_directory_urls: false

# Repository
repo_name: lbwanga
repo_url: https://github.com/lbwanga/lbwanga.github.io

# Contents
nav:
  - Java: 
    - Java基础: Java/Java.md
    - Java集合: Java/Java集合.md
  - JUC: JUC/JUC.md
  - 设计模式: 设计模式/设计模式.md

# Theme
theme:
  name: material
  highlightjs: true
  logo: assets/logo.png
  favicon: assets/logo.png
  language: 'zh'
  # colors: https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
  palette:
    primary: white
    accent: blue

  features:
    - content.action.edit
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - navigation.tabs
    - navigation.instant
    

# Customization
extra:
  analytics: 
    provider: google
    property: G-XXXXXXXXXX
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.

copyright: Copyright &copy; 2019 - 2024 wang

plugins:
  - glightbox

# Extensions
markdown_extensions:
  # - document-offsets-injection:
      # debug: true
  - admonition
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: ""
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html